### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by brunetton** [hbiyik/service.subtitles.subscene#2]
Hi, can you add a readme to explain what this repo is ?
Is it a fork of [CrowleyAJ's "official" Kodi addon](https://github.com/manacker/service.subtitles.subscene) for subscene.com website ? Or did you wrote a totaly new scrapper ?

Thanks !

**Comment by hbiyik** [comment]
it is / was a totally new scraper, but didnt check if it is working for a while
